### ISSUE TITLE
[Feature Request] User configurable key bindings

### ISSUE THREAD

**Issue by rzzr** [jediwade/brackets-htmlformat#1]
Let me first say that this extension is amazingly useful. It's surprising there isn't something like this included in Brackets by itself.

That being said, the best thing you could do with this is allow completely customizable shortcuts instead of only including some of the more common ones... like how you can map any key binding to insert any arbitrary string of text with Vim.

Imagine any conceivable shortcut instead of just a few! Would this be possible?

**Comment by jediwade** [comment]
Thank you for your message. It's good to know that my extension is being
used and enjoyed. I build HTML emails for a living and my co-workers were
talking about this awesome new app called Brackets that I should try out. I
did, but discovered it didnt have basic things like being able to bold or
italicize copy like I could easily do in Dreamweaver (yes, I admit I was
using Dreamweaver). That was actually the driving force behind me wanting
to build this extension.

I can certainly look into creating custom tags or code snippets to insert.
At the moment, I am more focused on fixing bugs and any errors that come
from using it. I am a total noob at this Brackets extension development. I
only recently discovered the built-in Developer Tools were you can see
errors caused by anything and everything running inside Brackets.

The thing I am focused on at the moment is fixing the issues around the
"Insert empty tag" feature. It was quite a hassle to figure out how to get
it to duplicate what you type in a different location. The biggest problem
is having it know that you are done typing. I contemplated removing the
"Insert empty tag" feature completely, but havent quite gotten there yet.

Another bug Im looking at is the adding and removing of the HTML Format
menu in the menu bar when you switch between different documents. I
currently have it setup so that it removes the menu if you arent in an HTML
document and then add it back when you switch to an HTML compatible
document. Apparently adding it back is causing errors even though I thought
I was properly removing it and nulling out the menu object.

Once I can get these errors sorted out, I can certainly look into adding in
custom tags or even full on code snippets. I dont see why it wouldnt be
possible. The effort would be creating a saved preference for custom
strings and building/adding to the preference list. Another feature I was
thinking about adding was trying to detect if you are in a stylesheet or
have the cursor within a <head> or inline style block and any of the tags
that have a style equivalent would insert that style in that inline style
or style definition.

Thank you again for your feedback.

**Comment by rzzr** [comment]
Your a cool guy Wade. Thank you for all that you do and have done already,
and hold on to the power of programming... it can change the world
dramatically with effective application.

Thanks again

**Comment by jediwade** [comment]
I know it has been a while since I last replied but I just updated the extension with some minor bug fixes and thought this was a good time to report. At this point in time I am not going to consider this feature request. There are many extensions that allow the insertion of custom code snippets and right now Im going to consider that beyond the original intent and scope of this extension. It might be considered for future updates, but not at this time.
