### ISSUE TITLE
Insert empty tag bug

### ISSUE THREAD

**Issue by qoalu** [jediwade/brackets-htmlformat#4]
When inserting empty tag multiple times the closing tag is filled with a multiplied number of added characters depending on how many times the empty tag shortcut (CTRL T) was used.

[Screen](https://cl.ly/2X3R0a0F2t1F)

The cause is probably a variable (_lng?) not being reset.

**Comment by jediwade** [comment]
I know the issue you speak of. It seemed like it was a Windows 10 only issue because it never happened on my Mac at home or my previous job.

This morning I tested it again on my computer at work and it is no longer doing the extra inserts. Can you update to the latest version of Brackets as well as the latest version of this extension and let me know if you experience the problem still? Also, what OS are you on?

I have tried creating multiple empty tags now and it appears to be functioning as expected now. I even deleted my local copy of the extension and downloaded it through the Extensions Manager in Brackets to make sure I was using a clean copy when trying to replicate the problem again.

**Comment by jediwade** [comment]
So for reasons I cannot explain, the bug seems to have been fixed. I installed Windows 10 using Bootcamp on my Macbook Air at home, got it fully up-to-date on security fixes and such, installed Brackets, then finally installed this extension and started using the Insert Empty Tag feature and it works as expected. I don't know if it was from my last update, which doesn't seem to make much sense to me looking at the differences between 0.3.8 and 0.3.9, or a Windows 10 update fixed whatever was causing it to have problems in the first place.

Can you make sure you are up to date on Windows patches, security updates, etc and try using the latest version of Brackets (if you weren't already) as well as the latest version of this extension and report your results?

**Comment by qoalu** [comment]
Updated to 0.3.9 and now there is no issue with the empty tag. Seems weird for it to happen on Windows 10 only. I figured Brackets is JavaScript based and is using the same engine across platforms.

But it works now, thank you!

**Comment by jediwade** [comment]
Completely agree. I was most confused on the issues with it just being problematic on Windows 10. A few weeks ago, I had a co-worker with a Windows 7 computer download Brackets and then my extension, and he didn't have any problems. I can only speculate as to why it was fixed from my changes.
