### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jgyo** [jediwade/brackets-htmlformat#6]
Installing failed with the error "The extension encountered an error while starting up."

No menu is created by the extension. If I close Brackets and reopen I get a dialog box from the extension, but still no new menu.

I am using Brackets release 1.12 build 1.12.0-17621

**Comment by jediwade** [comment]
This might be solved by me adding the following to the main.js code (more a note for myself):

require.config({
	paths: {
		"text":"lib/text",
		"i18n":"lib/i18n"
	},
	locale:brackets.getLocale()
});

Until I can fix this, if you open the Debug menu in Brackets and click "Reload with Extensions" (or F5 for Windows, maybe CMD+R for Mac) it should work after that.

**Comment by jediwade** [comment]
I could not get this replicated on my Windows 10 PC at home but could on my Windows 10 PC at work. I'm pretty sure my work computer is running the same version of Brackets that you and my home PC are using. Because I couldn't replicate it at home, I will have to wait until work on Monday to research it again. It might just end up being rolled into a big update I have been working on since reloading Brackets makes it work (in my experience at work anyway).
